name: Frontend workflow

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    uses: org-547/reusable/.github/workflows/img-build-push.yml@main
    with:
      app-component: app-client-2
      container: front-cnt
      port: 3000
    secrets:  
      docker-uname: ${{ secrets.DOCKER_UNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN}}

  Change-image-tag-and-deploy:
    needs: [Image-build-push]
    runs-on: self-hosted

    outputs:
      awk-out: ${{ steps.get-line.outputs.awk-out }}

    steps:  
      - name: Set up Git
        run: |
          git config --global user.name 'Tereza'
          git config --global user.email 'an3146073@gmail.com'

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIV_KEY }}
          private-key-name: github

      - name: Clone target repository
        run: git clone git@github.com:org-547/app-client-2.git

      - name: Change frontend image-tag
        working-directory: app-server-2
        run: sed -E -i'' "s/(.*app-client-2:).*/\1${GITHUB_SHA::7}/" 'docker-compose.yml'

      - name: Checking containers existence
        run: |
          for cnt in front-cnt back-cnt pg-cnt
          do
            if docker ps -a --format '{{.Names}}' | grep -q "$cnt"; then
              echo "Container with name $cnt already exists!"
              docker stop "$cnt" || true
              docker rm "$cnt" || true
            fi
          don

      - name: Execute awk command for extract necessary line
        id: get-line
        working-directory: app-server-2
        run: echo "awk-out=$(awk '/undefined-back-tag$/')" >> $GITHUB_OUTPUT

      - name: Checking line content
        run: |
          line=${{ steps.get-line.outputs.awk-out }}
          if [[ $line != *"undefined-back-tag"* ]]; then
            docker-compose down
            docker-compose up -d
          fi  
