name: Frontend workflow

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    uses: org-547/reusable/.github/workflows/img-build-push.yml@main
    with:
      app-component: app-client-2
      container: front-cnt
      port: 3000
    secrets:  
      docker-uname: ${{ secrets.DOCKER_UNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN}}

  Change-image-tag-and-deploy:
    needs: [Image-build-push]
    runs-on: self-hosted

    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}

    steps:
      - name: Check out other repo from same organization
        uses: actions/checkout@v3
        with:
          repository: org-547/for-compose
          ref: main

      #- name: Install docker compose
        #run: |
          #echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$USER
          #printf 'student\n' | sudo apt install docker-compose -y
          #echo "student" | sudo -S apt update
          #docker-compose --version
          #echo "Hello from me"

      - name: Extract current backend image-tag
        id: get-tag
        run: |
          echo "another message"
          CURRENT_BACK_TAG=$(grep -oP '(?<=image: terezabisharyan/app-server-2:)\${BACK_TAG}' docker-compose.yml)
          echo "tag=$CURRENT_BACK_TAG" >> $GITHUB_OUTPUT
          echo "Current backend image-tag is: $CURRENT_BACK_TAG" 

      - name: Check frontend container existence
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q 'front-cnt'; then
            echo "Container with name 'front-cnt' already exists!"
            docker stop front-cnt || true
            docker rm front-cnt || true
          fi 

      - name: Check backend container existence
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q 'back-cnt'; then
            echo "Container with name 'back-cnt' already exists!"
            docker stop back-cnt || true
            docker rm back-cnt || true
          fi 

      - name: Check postgres container existence
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q 'pg-cnt'; then
            echo "Container with name 'pg-cnt' already exists!"
            docker stop pg-cnt || true
            docker rm pg-cnt || true
          fi    

      - name: Docker-compose down and up
        run: |
          if [ ${{ steps.get-tag.outputs.tag }}  == ${BACK_TAG} ]; then
            export BACK_TAG=first
          fi  
          export FRONT_TAG=${GITHUB_SHA::7}
          echo "Backend tag is: $BACK_TAG"
          docker-compose down 
          docker-compose up -d
