name: Frontend workflow

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    uses: org-547/reusable/.github/workflows/img-build-push.yml@main
    with:
      app-component: app-client-2
      container: front-cnt
      port: 3000
    secrets:  
      docker-uname: ${{ secrets.DOCKER_UNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN}}

  Change-image-tag-and-deploy:
    needs: [Image-build-push]
    runs-on: self-hosted

    env:
      path: ../../app-server-2/app-server-2/app-server-2
    
    defaults:
      run:
        working-directory: ${{ env.path }}

    steps:  
    
      - name: Change frontend image-tag
        run: sed -E -i'' "s/(.*app-client-2:).*/\1${GITHUB_SHA::7}/" 'docker-compose.yml'

      - name: Checking containers existence
        run: |
          for cnt in front-cnt back-cnt pg-cnt
          do
            if docker ps -a --format '{{.Names}}' | grep -q "$cnt"; then
              echo "Container with name $cnt already exists!"
              docker stop "$cnt" || true
              docker rm "$cnt" || true
            fi
          done

      - name: Checking line content
        run: |
          pwd
          ls -lt
          if grep -q 'undefined' <<< $(awk '/undefined-back-tag$/' ./docker-compose.yml); then
            echo "Backend image-tag is not been determined yet!"
          else  
            docker compose down
            docker compose up -d
          fi  
